### ISSUE TITLE
pyCircos implementation

### ISSUE THREAD

**Issue by KonoganB** [ponnhide/pyCircos#2]
Hello! i'd like to implement pyCircos into my Tool, but I do not manage to do it with the given doc. I can't even run the example scripts. Would you mind helping me out?

**Comment by ponnhide** [comment]
Sorry for my late response and thank you for interesting with my pyCircos. I made pyCricos as just hobby scripts, so I didn't manage in recent. However, I have the plan to update the pyCircos within a month and I'll prepare curated README. Please wait and sorry for the inconvenience.

**Comment by akukalev** [comment]
Hi, same question from my side. I was excited to find a python package for circos plots, but I'm not even able to run examples code.  It would be really nice to see more details and/or validated examples.

**Comment by ponnhide** [comment]
I'm sorry for the inconvenience. Which kind of error did you face?

**Comment by bw2** [comment]
One that currently doesn't work is this line  https://github.com/ponnhide/pyCircos/blob/master/sample/eukaryote1/eukaryote1.py#L25
produces 
`AttributeError: module 'pycircos' has no attribute 'GENOME'`

**Comment by bw2** [comment]
I see the main class is now called Gcircle, and the tutorial / how_to_use example does work.
