### ISSUE TITLE
Tickplot examples?

### ISSUE THREAD

**Issue by GanizaniSitara** [ponnhide/pyCircos#22]
Hi, I'm really struggling to get labels oriented by 90 degrees. The previous issue has been closed as tickplot implemented. Are there any working examples of this please?

(very nice lib by the way, thank you for having created it).

**Comment by moshi4** [comment]
Hi, @GanizaniSitara

> I'm really struggling to get labels oriented by 90 degrees.

What you want to do is create a plot like the one below?

![pycircos_tickplot_example](https://user-images.githubusercontent.com/41852815/183252480-1387320d-ad39-4851-8c3c-4bfba58d08e3.png)

You can refer to a working example for the above plot from my previous PR(#15).

___

:warning: This PR is not included in the latest v0.3.0 release. Note that you need to install the development version with the following command to run the working example.

    pip install git+https://github.com/ponnhide/pyCircos.git
