### ISSUE TITLE
Bug class Gcircle(object):

### ISSUE THREAD

**Issue by JLTrincado** [ponnhide/pyCircos#5]
Dear authors,

Class definition in python is without parenthesis. Line 22 on pycircos.py shows like this:

```
class Gcircle(object):
```
But it should be without the parenthesis:
```
class Gcircle:
```

Changing this, the package goes smooth.

Thanks for this tool.

Best,
Juanlu.

**Comment by ponnhide** [comment]
You are right.. I forgot that Python3 don't need parenthesis for a class declaration.
